### PR TITLE
Upgrade to Quarkus 3

### PR DESCRIPTION
**Pull request by gsmet**
Hey there,

Here is a PR to update to Quarkus 3.

It would be nice if you could merge it and release a new major version (`1.0.0` ?) before April 25th so that it's ready for the announcement.

Please ping me when the release is done so that I can include it in our automatic update recipes.

Thanks!

### CODE REVIEW

**Comment by gastaldi** [comment]
It looks like the repository isn't maintained for awhile, @chberger would you be interested in being a maintainer to this extension?

**Comment by chberger** [comment]
I haven't checked the extension in detail yet, but it doesn't seem too complex. So, yes I would love to maintain this extension.

**Comment by gastaldi** [comment]
Excellent! I created https://github.com/quarkiverse/quarkiverse-devops/pull/175 adding you as a maintainer. Welcome to the Quarkiverse! Take a look at the Checklist when you are ready: https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created

**Review by chberger — CHANGES_REQUESTED** [review]
Let's use the Quarkus LTE version (3.2.5.Final as of now)

**Comment by gastaldi** [comment]
@all-contributors add @chberger for code and maintenance

**Pull request merged**
