### PR TITLE
chore(deps): update to Quarkus 3.15.x LTS version

### PR DESCRIPTION
**Pull request by wjglerum**
Leveraged `quarkus update` to migrate the project to the latest version of the Quarkus LTS

The most notable change is the relocation of the rest modules

### CODE REVIEW

**Review by chberger — COMMENTED** [review]
Looks good to me! Could you also update the Dependabot configuration to only notify about patch updates for version 3.15 - many thanks!

**Comment by chberger** [comment]
It looks like there's also an update regarding the configuration documentation for extensions. You can find the details here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#publishing-the-config-documentation.

Let me know if i should take over some parts.

**Comment by wjglerum** [comment]
> It looks like there's also an update regarding the configuration documentation for extensions. You can find the details here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#publishing-the-config-documentation.
> 
> Let me know if i should take over some parts.

thanks, missed that bit but had seen it before 🙈 

I updated the PR accordingly

**Comment by wjglerum** [comment]
Let me know if it looks good, before making another release we should probably also update Wiremock to the latest version by merging this Dependabot PR https://github.com/quarkiverse/quarkus-wiremock/pull/168

**Comment by chberger** [comment]
> Let me know if it looks good, before making another release we should probably also update Wiremock to the latest version by merging this Dependabot PR #168

Sure, I'll do so - thanks for your support

**Pull request merged**
