### PR TITLE
Allow resource loading to be done from the Classpath

### PR DESCRIPTION
**Pull request by geoand**
The context of this is [this](https://github.com/quarkiverse/quarkus-langchain4j/issues/446) issue where I would like to move away for custom WireMock handling to using this extension.

However in order to do so, I plan to have a custom module that contains both resources and supporting code, and for that work I need to have the resources loadable from the classpath

### CODE REVIEW

**Review by chberger — COMMENTED** [review]
@geoand Thank you very much! Overall it looks very good 🚀 . I would only vote for using ` config.effectiveFileMapping()` exclusively for accessing the mapping path (also in the filesystem case). At the moment we check and call either `config.filesMapping` or `config.effectiveFileMapping()` although the latter could handle all scenarios. wdyt?

**Comment by geoand** [comment]
Yeah, I was pondering the same when I wrote this. 

PR updated as per your suggestion

**Review by chberger — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
🙏🏼

**Comment by geoand** [comment]
👌

**Pull request closed without merging**
