### PR TITLE
Upgrade Quarkus to 3.1.0-Final

### PR DESCRIPTION
**Pull request by diversit**

### CODE REVIEW

**Comment by chberger** [comment]
@gastaldi It would be nice to use this extension with ``Quarkus 3``. Seems like the change is not that invasive. :-)

**Comment by gastaldi** [comment]
@chberger agreed, I asked the @quarkiverse/quarkiverse-wiremock team to review it

**Comment by gastaldi** [comment]
Actually let's close this and have #20 updated to use the Quarkus LTE version (3.2.4.Final as of now)

**Comment by chberger** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
