### PR TITLE
feat: upgrade and switch to WireMock standalone

### PR DESCRIPTION
**Pull request by wjglerum**
https://github.com/wiremock/wiremock/releases

Also see https://github.com/quarkiverse/quarkus-wiremock/pull/56

### CODE REVIEW

**Comment by wjglerum** [comment]
@chberger what's your plan for a 1.0 release btw? Do we need anything else?

**Comment by chberger** [comment]
I'm thinking about a solution to enable extensions in a more generic way. IMHO the current way is very limited ...

However, if it's not a problem to introduce new major versions regularly, then I'm fine to release `1.0`. Otherwise I would need more time to think about the current configuration capabilities and how to adapt them ...

**Review by chberger — APPROVED** [review]
LGTM - thanks!

**Comment by wjglerum** [comment]
> I'm thinking about a solution to enable extensions in a more generic way. IMHO the current way is very limited ...
> 
> However, if it's not a problem to introduce new major versions regularly, then I'm fine to release `1.0`. Otherwise I would need more time to think about the current configuration capabilities and how to adapt them ...

Yeah we could do the extensions in another release right? And start with the basics for now, that will already be valuable for other people too.

**Pull request merged**
